prooph_event_store:
    projection_managers:
        default:
            event_store: Prooph\EventStore\Pdo\PostgresEventStore
            connection: 'doctrine.pdo.connection'
            projections:
                bank_account_projection:
                    read_model: App\Projection\BankAccount\BankAccountReadModel
                    projection: App\Projection\BankAccount\BankAccountProjection
                transaction_projection:
                    read_model: App\Projection\Transaction\TransactionReadModel
                    projection: App\Projection\Transaction\TransactionProjection

services:
    Prooph\EventStore\Pdo\PostgresEventStore:
        arguments:
          - '@prooph_event_store.message_factory'
          - '@doctrine.pdo.connection'
          - '@prooph_event_store.aggregate_stream_strategy'

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.aggregate_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\PostgresAggregateStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator

